
import type { User, Product, Order } from './types';

const now = Date.now();

export const mockUsers: User[] = [
  {
    uid: 'vendor1',
    name: 'Raju Chaat',
    email: 'raju@chaat.com',
    phone: '+919876543210',
    role: 'vendor',
    location: 'T. Nagar, Chennai',
    verified: true,
    createdAt: now - 86400000 * 10,
  },
  {
    uid: 'vendor2',
    name: 'Dilli Biryani',
    email: 'dilli@biryani.com',
    phone: '+919876543211',
    role: 'vendor',
    location: 'Velachery, Chennai',
    verified: true,
    createdAt: now - 86400000 * 5,
  },
  {
    uid: 'vendor3',
    name: 'Mumbai Vadapav',
    email: 'mumbai@vadapav.com',
    phone: '+919876543212',
    role: 'vendor',
    location: 'Nungambakkam, Chennai',
    verified: false,
    createdAt: now - 86400000 * 2,
  },
  {
    uid: 'vendor4',
    name: 'Kolkata Kathi Rolls',
    email: 'kolkata@rolls.com',
    phone: '+919876543213',
    role: 'vendor',
    location: 'Adyar, Chennai',
    verified: true,
    createdAt: now - 86400000 * 12,
  },
  {
    uid: 'vendor5',
    name: 'Bangalore Dosa',
    email: 'bangalore@dosa.com',
    phone: '+919876543214',
    role: 'vendor',
    location: 'Anna Nagar, Chennai',
    verified: true,
    createdAt: now - 86400000 * 8,
  },
  {
    uid: 'supplier1',
    name: 'FreshMart',
    email: 'contact@freshmart.com',
    phone: '+918765432109',
    role: 'supplier',
    location: 'Koyambedu, Chennai',
    verified: true,
    createdAt: now - 86400000 * 30,
  },
  {
    uid: 'supplier2',
    name: 'LocalBazaar',
    email: 'support@localbazaar.com',
    phone: '+918765432108',
    role: 'supplier',
    location: 'Mylapore, Chennai',
    verified: true,
    createdAt: now - 86400000 * 25,
  },
  {
    uid: 'supplier3',
    name: 'Organic Spices Inc.',
    email: 'hello@organicspices.com',
    phone: '+918765432107',
    role: 'supplier',
    location: 'Guindy, Chennai',
    verified: true,
    createdAt: now - 86400000 * 20,
  },
  {
    uid: 'supplier4',
    name: 'Quality Oils',
    email: 'sales@qualityoils.com',
    phone: '+918765432106',
    role: 'supplier',
    location: 'Ambattur, Chennai',
    verified: true,
    createdAt: now - 86400000 * 15,
  },
  {
    uid: 'supplier5',
    name: 'Farm Fresh Veggies',
    email: 'farmfresh@veggies.com',
    phone: '+918765432105',
    role: 'supplier',
    location: 'Sholinganallur, Chennai',
    verified: false,
    createdAt: now - 86400000 * 8,
  },
  {
    uid: 'supplier6',
    name: 'All India Grocers',
    email: 'sales@aigrocers.com',
    phone: '+918765432104',
    role: 'supplier',
    location: 'Purasawalkam, Chennai',
    verified: true,
    createdAt: now - 86400000 * 40,
  },
  {
    uid: 'supplier7',
    name: 'South Staples',
    email: 'contact@southstaples.com',
    phone: '+918765432103',
    role: 'supplier',
    location: 'Triplicane, Chennai',
    verified: true,
    createdAt: now - 86400000 * 35,
  },
];

export const mockProducts: Product[] = [
  // Vegetables from FreshMart (supplier1)
  { id: 'prod1', name: 'Tomatoes', category: 'Vegetables', pricePerKg: 25, stockKg: 100, emoji: '🍅', supplierId: 'supplier1', supplierName: 'FreshMart', deliveryRadiusKm: 10, createdAt: now - 86400000 * 3 },
  { id: 'prod2', name: 'Onions', category: 'Vegetables', pricePerKg: 22, stockKg: 150, emoji: '🧅', supplierId: 'supplier1', supplierName: 'FreshMart', deliveryRadiusKm: 10, createdAt: now - 86400000 * 3 },
  { id: 'prod3', name: 'Potatoes', category: 'Vegetables', pricePerKg: 20, stockKg: 200, emoji: '🥔', supplierId: 'supplier1', supplierName: 'FreshMart', deliveryRadiusKm: 10, createdAt: now - 86400000 * 3 },
  { id: 'prod20', name: 'Cauliflower', category: 'Vegetables', pricePerKg: 35, stockKg: 60, emoji: '🥦', supplierId: 'supplier1', supplierName: 'FreshMart', deliveryRadiusKm: 10, createdAt: now - 86400000 * 3 },
  { id: 'prod21', name: 'Spinach', category: 'Vegetables', pricePerKg: 15, stockKg: 70, emoji: '🥬', supplierId: 'supplier1', supplierName: 'FreshMart', deliveryRadiusKm: 10, createdAt: now - 86400000 * 3 },

  // Vegetables from Farm Fresh Veggies (supplier5)
  { id: 'prod4', name: 'Carrots', category: 'Vegetables', pricePerKg: 30, stockKg: 80, emoji: '🥕', supplierId: 'supplier5', supplierName: 'Farm Fresh Veggies', deliveryRadiusKm: 15, createdAt: now - 86400000 * 2 },
  { id: 'prod5', name: 'Cucumbers', category: 'Vegetables', pricePerKg: 18, stockKg: 9, emoji: '🥒', supplierId: 'supplier5', supplierName: 'Farm Fresh Veggies', deliveryRadiusKm: 15, createdAt: now - 86400000 * 2 },
  { id: 'prod22', name: 'Bell Peppers', category: 'Vegetables', pricePerKg: 50, stockKg: 50, emoji: '🫑', supplierId: 'supplier5', supplierName: 'Farm Fresh Veggies', deliveryRadiusKm: 15, createdAt: now - 86400000 * 2 },
  
  // MULTIPLE SUPPLIER PRODUCTS
  { id: 'prod1b', name: 'Tomatoes', category: 'Vegetables', pricePerKg: 23, stockKg: 80, emoji: '🍅', supplierId: 'supplier5', supplierName: 'Farm Fresh Veggies', deliveryRadiusKm: 12, createdAt: now - 86400000 * 3 },
  { id: 'prod2b', name: 'Onions', category: 'Vegetables', pricePerKg: 25, stockKg: 120, emoji: '🧅', supplierId: 'supplier5', supplierName: 'Farm Fresh Veggies', deliveryRadiusKm: 12, createdAt: now - 86400000 * 3 },
  { id: 'prod2c', name: 'Onions', category: 'Vegetables', pricePerKg: 21, stockKg: 250, emoji: '🧅', supplierId: 'supplier2', supplierName: 'LocalBazaar', deliveryRadiusKm: 5, createdAt: now - 86400000 * 3 },


  // Oils from Quality Oils (supplier4)
  { id: 'prod6', name: 'Sunflower Oil', category: 'Oils', pricePerKg: 120, stockKg: 50, emoji: '🌻', supplierId: 'supplier4', supplierName: 'Quality Oils', deliveryRadiusKm: 20, createdAt: now - 86400000 * 5 },
  { id: 'prod7', name: 'Mustard Oil', category: 'Oils', pricePerKg: 150, stockKg: 40, emoji: '🌿', supplierId: 'supplier4', supplierName: 'Quality Oils', deliveryRadiusKm: 20, createdAt: now - 86400000 * 5 },
  { id: 'prod8', name: 'Olive Oil', category: 'Oils', pricePerKg: 400, stockKg: 20, emoji: '🫒', supplierId: 'supplier4', supplierName: 'Quality Oils', deliveryRadiusKm: 20, createdAt: now - 86400000 * 5 },
  { id: 'prod23', name: 'Coconut Oil', category: 'Oils', pricePerKg: 220, stockKg: 60, emoji: '🥥', supplierId: 'supplier4', supplierName: 'Quality Oils', deliveryRadiusKm: 20, createdAt: now - 86400000 * 5 },
  { id: 'prod24', name: 'Ghee', category: 'Dairy', pricePerKg: 550, stockKg: 30, emoji: '🧈', supplierId: 'supplier4', supplierName: 'Quality Oils', deliveryRadiusKm: 20, createdAt: now - 86400000 * 5 },


  // Spices from Organic Spices Inc. (supplier3)
  { id: 'prod9', name: 'Turmeric Powder', category: 'Spices', pricePerKg: 200, stockKg: 60, emoji: '🌶️', supplierId: 'supplier3', supplierName: 'Organic Spices Inc.', deliveryRadiusKm: 50, createdAt: now - 86400000 * 7 },
  { id: 'prod10', name: 'Chilli Powder', category: 'Spices', pricePerKg: 250, stockKg: 55, emoji: '🥵', supplierId: 'supplier3', supplierName: 'Organic Spices Inc.', deliveryRadiusKm: 50, createdAt: now - 86400000 * 7 },
  { id: 'prod11', name: 'Coriander Powder', category: 'Spices', pricePerKg: 180, stockKg: 70, emoji: '🌿', supplierId: 'supplier3', supplierName: 'Organic Spices Inc.', deliveryRadiusKm: 50, createdAt: now - 86400000 * 7 },
  { id: 'prod25', name: 'Cumin Seeds', category: 'Spices', pricePerKg: 300, stockKg: 40, emoji: '✨', supplierId: 'supplier3', supplierName: 'Organic Spices Inc.', deliveryRadiusKm: 50, createdAt: now - 86400000 * 7 },
  { id: 'prod26', name: 'Black Pepper', category: 'Spices', pricePerKg: 450, stockKg: 35, emoji: '⚫', supplierId: 'supplier3', supplierName: 'Organic Spices Inc.', deliveryRadiusKm: 50, createdAt: now - 86400000 * 7 },

  // Grains from LocalBazaar (supplier2)
  { id: 'prod12', name: 'Basmati Rice', category: 'Grains', pricePerKg: 90, stockKg: 300, emoji: '🍚', supplierId: 'supplier2', supplierName: 'LocalBazaar', deliveryRadiusKm: 8, createdAt: now - 86400000 * 4 },
  { id: 'prod13', name: 'Lentils (Toor Dal)', category: 'Grains', pricePerKg: 110, stockKg: 120, emoji: '🥣', supplierId: 'supplier2', supplierName: 'LocalBazaar', deliveryRadiusKm: 8, createdAt: now - 86400000 * 4 },
  { id: 'prod14', name: 'Ginger', category: 'Vegetables', pricePerKg: 80, stockKg: 45, emoji: '🫚', supplierId: 'supplier2', supplierName: 'LocalBazaar', deliveryRadiusKm: 8, createdAt: now - 86400000 * 4 },
  { id: 'prod15', name: 'Garlic', category: 'Vegetables', pricePerKg: 120, stockKg: 40, emoji: '🧄', supplierId: 'supplier2', supplierName: 'LocalBazaar', deliveryRadiusKm: 8, createdAt: now - 86400000 * 4 },
  { id: 'prod27', name: 'Wheat Flour (Atta)', category: 'Grains', pricePerKg: 40, stockKg: 500, emoji: '🌾', supplierId: 'supplier2', supplierName: 'LocalBazaar', deliveryRadiusKm: 8, createdAt: now - 86400000 * 4 },


  // Products from All India Grocers (supplier6)
  { id: 'prod16', name: 'Paneer', category: 'Dairy', pricePerKg: 450, stockKg: 30, emoji: '🧀', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  { id: 'prod17', name: 'Chickpeas (Chana)', category: 'Grains', pricePerKg: 95, stockKg: 180, emoji: '🧆', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  { id: 'prod28', name: 'Yogurt (Curd)', category: 'Dairy', pricePerKg: 60, stockKg: 100, emoji: '🥛', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  
  // Products from South Staples (supplier7)
  { id: 'prod18', name: 'Idli Rice', category: 'Grains', pricePerKg: 60, stockKg: 250, emoji: '🍚', supplierId: 'supplier7', supplierName: 'South Staples', deliveryRadiusKm: 12, createdAt: now - 86400000 * 9 },
  { id: 'prod19', name: 'Urad Dal', category: 'Grains', pricePerKg: 130, stockKg: 140, emoji: '🥣', supplierId: 'supplier7', supplierName: 'South Staples', deliveryRadiusKm: 12, createdAt: now - 86400000 * 9 },
  { id: 'prod29', name: 'Rava (Semolina)', category: 'Grains', pricePerKg: 50, stockKg: 150, emoji: '🌾', supplierId: 'supplier7', supplierName: 'South Staples', deliveryRadiusKm: 12, createdAt: now - 86400000 * 9 },

  // Cleaners from All India Grocers (supplier6)
  { id: 'prod30', name: 'Cleaning Liquid', category: 'Cleaners', pricePerKg: 80, stockKg: 75, emoji: '🧼', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  { id: 'prod31', name: 'Garbage Bags (Roll)', category: 'Cleaners', pricePerKg: 100, stockKg: 100, emoji: '🗑️', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  { id: 'prod32', name: 'Paper Towels (Roll)', category: 'Cleaners', pricePerKg: 60, stockKg: 120, emoji: '🧻', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  { id: 'prod33', name: 'Dish Soap', category: 'Cleaners', pricePerKg: 90, stockKg: 80, emoji: '🧴', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },

  // Meat from All India Grocers (supplier6)
  { id: 'prod34', name: 'Chicken', category: 'Meat', pricePerKg: 250, stockKg: 50, emoji: '🍗', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  { id: 'prod35', name: 'Mutton', category: 'Meat', pricePerKg: 750, stockKg: 30, emoji: '🍖', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },

  // Fish from All India Grocers (supplier6)
  { id: 'prod36', name: 'Fish', category: 'Fish', pricePerKg: 350, stockKg: 40, emoji: '🐟', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },
  { id: 'prod37', name: 'Prawns', category: 'Fish', pricePerKg: 500, stockKg: 25, emoji: '🦐', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 6 },

  // Ready to Cook from South Staples (supplier7)
  { id: 'prod38', name: 'Idli/Dosa Batter', category: 'Ready to Cook', pricePerKg: 50, stockKg: 100, emoji: '🥣', supplierId: 'supplier7', supplierName: 'South Staples', deliveryRadiusKm: 12, createdAt: now - 86400000 * 1 },
  { id: 'prod39', name: 'Adai Batter', category: 'Ready to Cook', pricePerKg: 60, stockKg: 80, emoji: '🥞', supplierId: 'supplier7', supplierName: 'South Staples', deliveryRadiusKm: 12, createdAt: now - 86400000 * 1 },
  { id: 'prod40', name: 'Chapathi Dough', category: 'Ready to Cook', pricePerKg: 70, stockKg: 90, emoji: '🫓', supplierId: 'supplier7', supplierName: 'South Staples', deliveryRadiusKm: 12, createdAt: now - 86400000 * 1 },
  { id: 'prod41', name: 'Frozen Parotta', category: 'Ready to Cook', pricePerKg: 100, stockKg: 60, emoji: '🥐', supplierId: 'supplier6', supplierName: 'All India Grocers', deliveryRadiusKm: 25, createdAt: now - 86400000 * 2 },
];


export const mockOrders: Order[] = [
  {
    id: 'order1',
    vendorId: 'vendor1',
    vendorName: 'Raju Chaat',
    supplierId: 'supplier1',
    supplierName: 'FreshMart',
    productId: 'prod2',
    productName: 'Onions',
    quantity: 10,
    totalPrice: 220,
    status: 'Delivered',
    orderDate: now - 86400000 * 4,
    deliveryEta: now - 86400000 * 3,
    deliveryLocation: '123 Anna Salai, Chennai',
    paymentMethod: 'COD',
  },
  {
    id: 'order2',
    vendorId: 'vendor2',
    vendorName: 'Dilli Biryani',
    supplierId: 'supplier2',
    supplierName: 'LocalBazaar',
    productId: 'prod12',
    productName: 'Basmati Rice',
    quantity: 50,
    totalPrice: 4500,
    status: 'Shipped',
    orderDate: now - 86400000 * 2,
    deliveryEta: now + 86400000,
    deliveryLocation: '456 Velachery Main Road, Chennai',
    paymentMethod: 'Online',
  },
  {
    id: 'order3',
    vendorId: 'vendor1',
    vendorName: 'Raju Chaat',
    supplierId: 'supplier4',
    supplierName: 'Quality Oils',
    productId: 'prod6',
    productName: 'Sunflower Oil',
    quantity: 5,
    totalPrice: 600,
    status: 'Packed',
    orderDate: now - 86400000,
    deliveryEta: now + 86400000 * 2,
    deliveryLocation: '123 Anna Salai, Chennai',
    paymentMethod: 'Online',
  },
  {
    id: 'order4',
    vendorId: 'vendor3',
    vendorName: 'Mumbai Vadapav',
    supplierId: 'supplier1',
    supplierName: 'FreshMart',
    productId: 'prod3',
    productName: 'Potatoes',
    quantity: 25,
    totalPrice: 500,
    status: 'Pending',
    orderDate: now - 3600000,
    deliveryEta: now + 86400000 * 3,
    deliveryLocation: '789 Nungambakkam High Road, Chennai',
    paymentMethod: 'COD',
  },
  {
    id: 'order5',
    vendorId: 'vendor2',
    vendorName: 'Dilli Biryani',
    supplierId: 'supplier3',
    supplierName: 'Organic Spices Inc.',
    productId: 'prod10',
    productName: 'Chilli Powder',
    quantity: 2,
    totalPrice: 500,
    status: 'Delivered',
    orderDate: now - 86400000 * 5,
    deliveryEta: now - 86400000 * 4,
    deliveryLocation: '456 Velachery Main Road, Chennai',
    paymentMethod: 'COD',
  },
  {
    id: 'order6',
    vendorId: 'vendor4',
    vendorName: 'Kolkata Kathi Rolls',
    supplierId: 'supplier6',
    supplierName: 'All India Grocers',
    productId: 'prod16',
    productName: 'Paneer',
    quantity: 15,
    totalPrice: 6750,
    status: 'Pending',
    orderDate: now - 86400000 * 1,
    deliveryEta: now + 86400000 * 2,
    deliveryLocation: '10 Adyar Bridge Road, Chennai',
    paymentMethod: 'COD',
  },
  {
    id: 'order7',
    vendorId: 'vendor5',
    vendorName: 'Bangalore Dosa',
    supplierId: 'supplier7',
    supplierName: 'South Staples',
    productId: 'prod18',
    productName: 'Idli Rice',
    quantity: 30,
    totalPrice: 1800,
    status: 'Shipped',
    orderDate: now - 86400000 * 3,
    deliveryEta: now - 86400000 * 1,
    deliveryLocation: '22 T. Nagar, Chennai',
    paymentMethod: 'Online',
  },
];

    
